//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public int MemberID { get; set; }
        public string MailingUnitAndStreet { get; set; }
        public string MailingPostalCode { get; set; }
        public Nullable<int> MailingProvinceID { get; set; }
        public string ShippingUnitAndStreet { get; set; }
        public string ShippingPostalCode { get; set; }
        public Nullable<int> ShippingProvinceID { get; set; }
    }
}
