// Generated by Selenium IDE
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace UnitTestProject
{
    [TestFixture("chrome")]
    public class LoginJoiningTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            //ChromeOptions chromeOptions = new ChromeOptions();
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void login()
        {
            driver.Navigate().GoToUrl("https://localhost:44339/");
            driver.Manage().Window.Size = new System.Drawing.Size(1655, 903);
            driver.FindElement(By.LinkText("Log in")).Click();
            driver.FindElement(By.Id("UserName")).Click();
            driver.FindElement(By.Id("UserName")).SendKeys("aaaa");
            driver.FindElement(By.Id("UserPassword")).Click();
            driver.FindElement(By.Id("UserPassword")).SendKeys("aase344@ssddd");
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("UserPassword")).Click();
            driver.FindElement(By.Id("UserPassword")).SendKeys("aase344@ssddd22@");
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(2)")).Click();
            driver.FindElement(By.Id("UserName")).Click();
            driver.FindElement(By.Id("UserName")).SendKeys("dzisaacs");
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("UserPassword")).Click();
            driver.FindElement(By.Id("UserPassword")).SendKeys("Test!077");
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.CssSelector("form:nth-child(2)")).Click();
            driver.FindElement(By.LinkText("CVGS")).Click();
        }

        [Test]
        public void Register()
        {
                driver.Navigate().GoToUrl("https://localhost:44339/");
                driver.Manage().Window.Size = new System.Drawing.Size(1655, 903);
                driver.FindElement(By.LinkText("Sign Up")).Click();
                driver.FindElement(By.Id("UserName")).Click();
                driver.FindElement(By.Id("UserName")).SendKeys("aksa");
                driver.FindElement(By.Id("UserPassword")).Click();
                driver.FindElement(By.Id("UserName")).Click();
                driver.FindElement(By.Id("UserName")).SendKeys("Almas");
                driver.FindElement(By.Id("UserPassword")).Click();
                driver.FindElement(By.Id("UserPassword")).SendKeys("test12#");
                {
                    var element = driver.FindElement(By.Id("UserEmail"));
                    Actions builder = new Actions(driver);
                    builder.MoveToElement(element).ClickAndHold().Perform();
                }
                {
                    var element = driver.FindElement(By.CssSelector(".form-horizontal"));
                    Actions builder = new Actions(driver);
                    builder.MoveToElement(element).Release().Perform();
                }
                driver.FindElement(By.CssSelector(".form-horizontal")).Click();
                driver.FindElement(By.Id("UserPassword")).Click();
                driver.FindElement(By.Id("UserPassword")).SendKeys("test12#12");
                driver.FindElement(By.Id("UserEmail")).Click();
                driver.FindElement(By.Id("UserEmail")).SendKeys("almas786.khan@gmail.com");
                driver.FindElement(By.XPath("(//input[@id=\'UserType\'])[2]")).Click();
                driver.FindElement(By.Id("CaptchaInputText")).Click();
                driver.FindElement(By.CssSelector(".btn")).Click();
                driver.FindElement(By.Id("CaptchaInputText")).Click();
                driver.FindElement(By.Id("CaptchaInputText")).SendKeys("50");
                driver.FindElement(By.Id("UserPassword")).Click();
                driver.FindElement(By.Id("UserPassword")).SendKeys("motumalik28@");
                driver.FindElement(By.CssSelector(".btn")).Click();
                driver.FindElement(By.LinkText("Back to Login")).Click();
            
        }
    }
}

